[pytest]
addopts = -q -s
markers =
    route: Тесты отрисовки маршрута
    route_block: Тесты блока выбора маршрута
    prepare_taxi: Тесты подготовки к заказу такси
    taxi_flow: Тесты заказа тарифа Такси (полный флоу)
    drive: Тесты тарифа Драйв
    xfail_bug: Ожидаемо падающие тесты (известные баги)
